/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erviani.saputri;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;
/**
 *
 * @author Asus
 */
public class NewJPanel extends javax.swing.JPanel { 
    String pilihan = "";
    double Hargabarang;
    int jumlah;
    double besardiscount;
    double kembalian;
    String Pilihan;
    double Harga;
    
    String count = "tidak ada disount";
    
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelTransaksi = new javax.swing.JLabel();
        txtTransaksi = new javax.swing.JTextField();
        labelBarang = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        comboBeli = new javax.swing.JComboBox<>();
        labelKembali = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        btnUlangi = new javax.swing.JButton();
        ComboPilihan = new javax.swing.JComboBox<>();
        labelDiskon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        txtTotalbelanja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelBayar = new javax.swing.JLabel();
        txtJumlahBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelHarga1 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("                   DATA TRANSAKSI");

        labelTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTransaksi.setText("ID Transaksi");

        txtTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransaksiActionPerformed(evt);
            }
        });

        labelBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBarang.setText("Nama Barang");

        labelHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelHarga.setText("Harga");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        comboBeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Beli", "1", "2", "3", "4", "5" }));
        comboBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBeliActionPerformed(evt);
            }
        });

        labelKembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKembali.setText("Kembalian ");

        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnUlangi.setText("Ulangi");
        btnUlangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangiActionPerformed(evt);
            }
        });

        ComboPilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan", "Vivo V19", "Samsung A20", "Realme V15", "Oppo Reno 4", "Asus", "Iphone 15 Pro" }));
        ComboPilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPilihanActionPerformed(evt);
            }
        });

        labelDiskon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDiskon.setText("Diskon");

        jLabel3.setText("%");

        labelTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotal.setText("Total Belanja");

        txtTotalbelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalbelanjaActionPerformed(evt);
            }
        });

        jLabel5.setText("Rp");

        labelBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelBayar.setText("Jumlah Bayar");

        txtJumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBayarActionPerformed(evt);
            }
        });

        jLabel7.setText("Rp");

        jLabel8.setText("Rp");

        jLabel9.setText("Rp");

        labelHarga1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelHarga1.setText("Jumlah Beli");

        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnProses))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKembali)
                            .addComponent(labelBayar)
                            .addComponent(labelTotal)
                            .addComponent(labelDiskon)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTransaksi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelHarga1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUlangi)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComboPilihan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTotalbelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(77, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTransaksi)
                    .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarang)
                    .addComponent(ComboPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHarga1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiskon)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotalbelanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(labelTotal))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBayar)
                    .addComponent(txtJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKembali)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(btnUlangi))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransaksiActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void txtTotalbelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalbelanjaActionPerformed
       
    }//GEN-LAST:event_txtTotalbelanjaActionPerformed

    private void txtJumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBayarActionPerformed

    private void ComboPilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPilihanActionPerformed
        // TODO add your handling code here:
        
        pilihan = String.valueOf(ComboPilihan.getSelectedItem());
        
        if(pilihan.equals("Pilihan")) {
            Harga = 0;
        }else if (pilihan.equals("Vivo V19")){
            Harga = 2000000;
        }else if (pilihan.equals("Samsung A20")){
            Harga = 1500000;
        }else if (pilihan.equals("Realme V15")){
            Harga = 3000000;
        }else if (pilihan.equals("Oppo Reno 4")){
            Harga = 5000000;
        }else if (pilihan.equals("Asus")){
            Harga = 1000000;
        }else if (pilihan.equals("Iphone 15 Pro")){
            Harga = 10000000;
        }
        
        txtHarga.setText( "" + Harga);
    }//GEN-LAST:event_ComboPilihanActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
     
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        
        Double totalBelanja = Double.parseDouble(txtTotalbelanja.getText());
        Double money = Double.parseDouble(txtJumlahBayar.getText());
        
        if (money == totalBelanja) {
            txtKembalian.setText("0");
        }else if(money < totalBelanja) {
            txtKembalian.setText("KURANG");
        }else {
            txtKembalian.setText("" + (money - totalBelanja));
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void comboBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBeliActionPerformed
        String discText = String.valueOf(comboBeli.getSelectedItem());
        Double totalBelanja = 0.0;
        if (discText == "Jumlah Beli") {
            totalBelanja = 0.0;
            count = "0";
            besardiscount = 1;        
        }else if (Integer.parseInt(String.valueOf(comboBeli.getSelectedItem())) == 1) {
            count = "5";
            besardiscount = 0.05;
            totalBelanja = Harga * 1 * besardiscount;
        } else if (Integer.parseInt(String.valueOf(comboBeli.getSelectedItem())) == 2) {
            count = "10";
            besardiscount = 0.1;
            totalBelanja = Harga * 2 * besardiscount;
        } else if (Integer.parseInt(String.valueOf(comboBeli.getSelectedItem())) == 3) {
            count = "15";
            besardiscount = 0.15;
            totalBelanja = Harga * 3 * besardiscount;
        } else if (Integer.parseInt(String.valueOf(comboBeli.getSelectedItem())) == 4) {
            count = "25";
            besardiscount = 0.25;
            totalBelanja = Harga * 4 * besardiscount;
        } else if (Integer.parseInt(String.valueOf(comboBeli.getSelectedItem())) == 5) {
            count = "30";
            besardiscount = 0.3;
            totalBelanja = Harga * 5 * besardiscount;
        }
        
        txtDiskon.setText(count);
        txtTotalbelanja.setText("" + totalBelanja);
    }//GEN-LAST:event_comboBeliActionPerformed

    private void btnUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangiActionPerformed
       txtTransaksi.setText("");
       ComboPilihan.setSelectedIndex(0);
       txtHarga.setText("");
       comboBeli.setSelectedIndex(0);
       txtDiskon.setText("");
       txtTotalbelanja.setText("");
       txtJumlahBayar.setText("");
       txtKembalian.setText("");
    }//GEN-LAST:event_btnUlangiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboPilihan;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnUlangi;
    private javax.swing.JComboBox<String> comboBeli;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelBarang;
    private javax.swing.JLabel labelBayar;
    private javax.swing.JLabel labelDiskon;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelHarga1;
    private javax.swing.JLabel labelKembali;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTransaksi;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlahBayar;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTotalbelanja;
    private javax.swing.JTextField txtTransaksi;
    // End of variables declaration//GEN-END:variables
}

